### ISSUE TITLE
Node 6 compatibility

### ISSUE THREAD

**Issue by Eragos** [ryan-rowland/albion-guildbot#10]
With node 6.11.1 I got the following exception:

> info: Connected
> info: Logged in as: AlbionBot - (xxxxxxxxxxxxxxxxxx)
> info: Checking battles...
> /opt/albion/albion-guildbot/lib/AlbionApi.js:12
>         ? '?' + Object.entries(queries).map((query) => query.join('=')).join('&')
>                        ^
> 
> TypeError: Object.entries is not a function
>     at baseRequest (/opt/albion/albion-guildbot/lib/AlbionApi.js:12:24)
>     at Object.getBattles (/opt/albion/albion-guildbot/lib/AlbionApi.js:42:12)
>     at checkBattles (/opt/albion/albion-guildbot/lib/index.js:56:10)
>     at Client.bot.on (/opt/albion/albion-guildbot/lib/index.js:47:3)
>     at emitNone (events.js:91:20)
>     at Client.emit (events.js:185:7)
>     at WebSocketConnection.triggerReady (/opt/albion/albion-guildbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:123:17)
>     at WebSocketConnection.checkIfReady (/opt/albion/albion-guildbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:139:61)
>     at GuildCreateHandler.handle (/opt/albion/albion-guildbot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
>     at WebSocketPacketManager.handle (/opt/albion/albion-guildbot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)

I figured out that include babel-polyfill will fix this. Maybe other people have the same problem.

To fix this, add the following:

```
diff --git a/package.json b/package.json
index 008ab1f..0135605 100644
--- a/package.json
+++ b/package.json
@@ -30,6 +30,7 @@
   },
   "dependencies": {
     "albion-api": "^1.3.0",
+    "babel-polyfill": "^6.26.0",
     "bluebird": "^3.5.0",
     "discord.js": "^11.2.1",
     "express": "^4.15.4",
diff --git a/src/index.js b/src/index.js
index 069dcf0..3054760 100644
--- a/src/index.js
+++ b/src/index.js
@@ -1,5 +1,7 @@
 'use strict';

+require('babel-polyfill');
+
 const Discord = require('discord.js');
 const FileSync = require('lowdb/adapters/FileSync');
 const logger = require('winston');
```

**Comment by ryan-rowland** [comment]
Supporting node 6 would be great! It seems like a common pain point. Mind opening a PR? 😃
